[package]
name = "prescott/dark-duty"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@^4"
Signal  = "sleitnick/signal@^2"